theme = "Qogir-dark"
icons = "awesome"

[[block]]
block = "disk_space"
path = "/"
alias = ""
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"
warning_swap = 10
critical_swap = 60

[[block]]
block = "cpu"
interval = 1
format = "{barchart} {utilization}% {frequency}GHz"

[[block]]
block = "net"
device = "enp1s0"
ip = true
#graph_up = true
#graph_down = true
interval = 5
use_bits = false

#[[block]]
#block = "load"
#interval = 1
#format = "{1m}"

#[[block]]
#block = "keyboard_layout"
#driver = "setxkbmap"
#interval = 15
#format = "{layout}"

[[block]]
block = "time"
interval = 60
format = "%a %m/%d %R"

[[block]]
block = "maildir"
interval = 60
inboxes = ["/home/noah/.local/share/mail/personal/INBOX", "/home/noah/.local/share/mail/work/INBOX"]
threshold_warning = 1
threshold_critical = 10
display_type = "new"
icon = true

[[block]]
block = "bluetooth"
mac = "00:0C:8A:7F:30:88"
label = " Bose"

[[block]]
block = "sound"

[[block]]
block = "music"
player = "mpd"
buttons = ["play"]
max_width = 25
marquee_interval = 2
